name: chatbotenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - flask
  - flask-cors
  - python-dotenv
  - pip:
      - langchain
      - langchain-community
      - langchain-google-genai
      - langchain-pinecone
      - pinecone-client
      - sentence-transformers
      - deep-translator
